# Trainign parameters
INPUT_SIZE = 784
NUM_CLASSES = 10
LEARNING_RATE = 0.001
BATCH_SIZE = 64
NUM_EPOCHS = 10
PRECISION = 'bf16-mixed'

#Dataset
DATA_DIR = "../data/"
NUM_WORKERS = 4
ACCELERATOR = 'cpu'